language: android

android:
  components:
    - tools # to get the new `repository-11.xml`
    - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
    - platform-tools
    - build-tools-24.0.2
    - android-24
    - sys-img-armeabi-v7a-android-24
    - extra-android-support
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - android-sdk-preview-license-52d11cd2
    - android-sdk-license-.+
    - google-gdk-license-.+

before_script:
  - curl ${GOOGLE_SERVICES_JSON} -o app/google-services.json
  - test -f local.properties.example && cp local.properties.example local.properties
  - test -f local.properties && sed -i -e s/BINTRAY_APIKEY/${BINTRAY_APIKEY}/g local.properties
  - test -f local.properties && sed -i -e s/BINTRAY_USER/${BINTRAY_USER}/g local.properties
  - test -f local.properties && sed -i -e s/BINTRAY_GPG_PASSWORD/${BINTRAY_GPG_PASSWORD}/g local.properties
  - echo no | android create avd --force -n test -t android-24 --abi armeabi-v7a
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - adb shell screencap -p /sdcard/before-key-82.png; adb pull /sdcard/before-key-82.png; curl --form "fileupload=@before-key-82.png" http://uploads.im/api?upload
  - adb shell input keyevent 82 &
  - adb shell screencap -p /sdcard/after-key-82.png; adb pull /sdcard/after-key-82.png; curl --form "fileupload=@after-key-82.png" http://uploads.im/api?upload

jdk:
  - oraclejdk8

os:
  - linux

script:
  - ./gradlew build connectedCheck

deploy:
  provider: script
  script: ./gradlew install bintrayUpload
  skip_cleanup: true
  on:
    tags: true

